build:
    nodes:
        php70:
            environment:
                php:
                    version: 7.0.20
            tests:
                override:
                    -
                        command: 'phpunit --coverage-clover=tests/cover'
                        coverage:
                            file: 'cover'
                            format: 'clover'
        php71:
            environment:
                php:
                    version: 7.1.12
            tests:
                override:
                    -
                        command: 'phpunit --coverage-clover=tests/cover'
                        coverage:
                            file: 'cover'
                            format: 'clover'
        php72:
            environment:
                php:
                    version: 7.2.0
            tests:
                override:
                    -
                        command: 'phpunit --coverage-clover=tests/cover'
                        coverage:
                            file: 'cover'
                            format: 'clover'
