tools:
    php_sim: false
    php_pdepend: true
    php_analyzer: true
    php_code_coverage: true
    external_code_coverage: false

build:
    nodes:
        php70:
            environment:
                php:
                    version: 7.0.20
            tests:
                override:
                    -
                        command: 'phpunit --coverage-clover=tests/cover'
                        coverage:
                            file: 'tests/cover'
                            format: 'clover'
        php71:
            environment:
                php:
                    version: 7.1.12
            tests:
                override:
                    -
                        command: 'phpunit --coverage-clover=tests/cover'
                        coverage:
                            file: 'tests/cover'
                            format: 'clover'
        php72:
            environment:
                php:
                    version: 7.2.0
            tests:
                override:
                    -
                        command: 'phpunit --coverage-clover=tests/cover'
                        coverage:
                            file: 'tests/cover'
                            format: 'clover'

    environment:
        php:
            version: 7.2
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=tests/cover'
                coverage:
                    file: 'tests/cover'
                    format: 'clover'

filter:
    excluded_paths: [vendor/*, tests/*, examples/*]